version: "3.6"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100k"
    max-file: "1"

networks:
  shared-services:
    external: true

services:
  gobarbar-back-end:
    restart: always
    container_name: gobarbar-back-end
    user: "${UID}:${GID}"
    build:
      context: .
      target: dev
    environment:
      - WATCH_FILES=${WATCH_FILES}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    command: yarn dev:server
    volumes:
      - .:/usr/app
    logging: *default-logging
    networks:
      - shared-services
