version: "3"

services:
  gobarbar-back-end:
    container_name: gobarbar-back-end
    build: .
    ports:
      - "3333:3333"
      - "9229:9229"
    command: yarn dev:server
    volumes:
      - .:/usr/app
